# Site settings
title: "Letterbox: Discover, Answer, Chat"
description: > # this means to ignore newlines until "baseurl:"
  Letterbox is a dating app that enables you to find people with compatible mindsets and opinions.

baseurl: "/letterbox-landing" # the subpath of your site, e.g. /blog/
url: "http://getletterbox.com" # the base hostname & protocol for your site

email: contact@getletterbox.com
facebook_link: "http://www.facebook.com/getletterbox"
app_store_link: "https://itunes.apple.com/us/app/letterbox-discover-answer/id1054804304?ls=1&mt=8"
play_store_link: "https://play.google.com/store/apps/details?id=com.getletterbox.letterbox"
web_link: "http://web.getletterbox.com"

# Build settings
markdown: kramdown


# Statistics
registered_users: "962"
female: "257"
male: "705"

letters: "6,046"
chats: "463"
messages: "11,691"

age_below_20: "35"
age_21_to_23: "475"
age_24_to_27: "323"
age_27_to_30: "57"
age_above_31: "72"
