# Site settings
title: "Letterbox: Discover, Answer, Chat"
description: > # this means to ignore newlines until "baseurl:"
  Letterbox is a dating app that enables you to find people with compatible mindsets and opinions.

baseurl: "/letterbox-landing" # the subpath of your site, e.g. /blog/
url: "http://letterboxdev.github.io" # the base hostname & protocol for your site

email: letterboxdev@gmail.com
facebook_link: ""
app_store_link: ""
play_store_link: ""

# Build settings
markdown: kramdown
