# Site settings
title: "Letterbox: Discover, Answer, Chat"
description: > # this means to ignore newlines until "baseurl:"
  Letterbox is a dating app that enables you to find people with compatible mindsets and opinions.

baseurl: "/letterbox-landing" # the subpath of your site, e.g. /blog/
url: "http://getletterbox.com" # the base hostname & protocol for your site

email: letterboxdev@gmail.com
facebook_link: "http://www.facebook.com/getletterbox"
app_store_link: ""
play_store_link: "https://play.google.com/store/apps/details?id=com.getletterbox.letterbox"

# Build settings
markdown: kramdown
